# Generated by Django 5.1.1 on 2024-09-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refaccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refaccion',
            name='imagePath',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
