# Generated by Django 5.1.1 on 2024-09-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refaccion', '0002_refaccion_imagepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccion',
            name='descripcion',
            field=models.TextField(max_length=1000),
        ),
    ]
